config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:index, :edit, :update, :new, :create] do
    resources :messages, only: [:index, :create]
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : "画像が投稿されています"
    else
      "まだメッセージはありません"
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
    @groups = current_user.groups.order(created_at: :DESC)
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    @group.users << current_user
    if @group.save
      redirect_to group_messages_path(@group), notice: "グループを作成しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group) , notice: "グループを編集しました"
    else
      render :edit
    end
  end

  def search
    @users = User.where.not(id: current_user.id).where('name LIKE(?)',"#{params[:keyword]}%").limit(20)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def group_params
    # user_ids = params[:group]["user_ids"]
    # user_ids << current_user.id.to_s
    # params.require(:group).permit(:name, user_ids: [])
    params.require(:group).permit(:name, { :user_ids => []})
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user).order(created_at: :ASC)
    respond_to do |format|
      format.html
      format.json{ @new_messages = @messages.where('id > ?', params[:message][:id])
        if @new_messages.present?
          @new_messages
        else
          render json: "No data"
        end }
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group)}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
    @groups = current_user.groups.order(created_at: :DESC)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit

  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def index

  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2 = "#{group.errors.full_messages.count}件のエラーが発生しました"
      %ul
        - group.errors.full_messages.each do |message|
          %li = message
  .chat-group-form__field
    .chat-group-form__field--left
      =f.label :name, class: "chat-group-form__label"
    .chat-group-form__field--right
      =f.text_field :name, class: "chat__group_name chat-group-form__input" , placeholder: "グループ名を入力して下さい"
  .chat-group-form__field.clearfix

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
  #user-search-result
  .chat-group-users
    .chat-group-user1.clearfix
      %chat-group-user__name
        =current_user.name
    / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    /
      <div id='chat-group-users'>
      <div class='chat-group-user clearfix' id="chat-group-user-#{current_user.id}">
      <input name='chat_group[user_ids][]' type='hidden' value="#{current_user.id}">
      <p class='chat-group-user__name'><%=current_user.name></p>
      </div>
      </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      =f.submit class: "chat-group-form__action-btn"
      / %input.chat-group-form__action-btn{"data-disable-with":"Save", name: "commit", type: "submit", value: "Save"}/

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.contents
  = render partial: "messages/content-left"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render "form", { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:rel => "stylesheet", :href => "https://use.fontawesome.com/releases/v5.3.1/css/all.css", :integrity => "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU", :crossorigin => "anonymous"}

  %body
    / .header チャットスペースが作成されました
    = render "layouts/notifications"
    = yield

app/views/messages/_chat.html.haml
.chat-box
  .chat
    %p.chat__user aa
    %p.chat__date 2018/10/08
    %p.chat__content こんにちは
  .chat
    %p.chat__user aa
    %p.chat__date 2018/10/09
    %p.chat__content Hello world

app/views/messages/_content-left.haml
.content-left
  .header-left
    .header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to new_group_path do
          = fa_icon 'edit', class: 'icon'
        / %i.fas.fa-edit
      / %li.list.fas.fa-cog
      %li.list
        = link_to edit_user_registration_path do
          = fa_icon 'cog', class: 'icon'


  .groups
    - @groups.each do |group|
      = link_to group_messages_path(group) do
        %p.groups__name
          =group.name
        %p.groups__messages
          =group.show_last_message

app/views/messages/_message.html.haml
.chat-box
  .chat{"data-id": "#{message.id}"}
    %p.chat__user
      = message.user.name
    %p.chat__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
    %p.chat__content
      =message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.contents
  = render partial: "content-left"


  .content-right
    .group
      %p.group__name
        = @group.name
      %p.group__member
        MEMBER:
        = @group.users.pluck(:name).join(",")
      =link_to edit_group_path(@group) do
        %p.group__btn Edit
    .chat-pad
      .chat-content
        = render partial: "message", collection: @messages


    .bottom-content
      .submit
        = form_for [@group, @message] , html: {id: "new_massage"} do |f|
          = f.text_field :content, class: 'form__message textbox', placeholder: 'type a message'
          .form__mask
            = f.label :image, class: 'form__mask__image' do
              = f.file_field :image, class: 'hidden imagebox'
              %i.far.fa-image
          = f.submit 'Send', class: 'form__submit'
        / %form
        /   %input.text{:type => "text", :placeholder => "type a message", :class => "submit__content"}
        /     .image
        /       %label.upload-label{for: "upload-icon"}
        /       %i.far.fa-image
        /         / = file_field :image, id: "upload-icon" ,:class => "ignore"
        /   %input.send{:type => "submit", :value => "Send" , :class => "submit__btn"}